name: Build & Push Windows Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          install: true

      - name: Set up Docker Buildx
        run: docker buildx create --name mybuilder --driver docker-container --use          

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Windows Docker Image
        run: docker buildx build --builder mybuilder --cache-from type=gha --cache-to type=gha,mode=max --file ./Dockerfile --platform windows/amd64 --tag ghcr.io/chandan0312/windows-app:late
        
      - name: Build and Push Image with Cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: windows/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/windows-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show Images
        run: docker images
